// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp-AxgvREKYOjC_sMH93H4aWMLh4sJ35g',
    appId: '1:1013497024846:web:a0f40994d0109f0138ce1f',
    messagingSenderId: '1013497024846',
    projectId: 'sanayirehberim-1e438',
    authDomain: 'sanayirehberim-1e438.firebaseapp.com',
    storageBucket: 'sanayirehberim-1e438.firebasestorage.app',
    measurementId: 'G-0Y2Z2YEV1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNhOQgAR-fILnWaBDAxgrcIG_5_Enk-zM',
    appId: '1:1013497024846:android:da8e8b512be4c3b538ce1f',
    messagingSenderId: '1013497024846',
    projectId: 'sanayirehberim-1e438',
    storageBucket: 'sanayirehberim-1e438.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJXGAweg3zE58gaqA6ZGppf8TFt5DLMhQ',
    appId: '1:1013497024846:ios:71b94d2da13e43cb38ce1f',
    messagingSenderId: '1013497024846',
    projectId: 'sanayirehberim-1e438',
    storageBucket: 'sanayirehberim-1e438.firebasestorage.app',
    iosBundleId: 'com.example.sanayirehberim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJXGAweg3zE58gaqA6ZGppf8TFt5DLMhQ',
    appId: '1:1013497024846:ios:71b94d2da13e43cb38ce1f',
    messagingSenderId: '1013497024846',
    projectId: 'sanayirehberim-1e438',
    storageBucket: 'sanayirehberim-1e438.firebasestorage.app',
    iosBundleId: 'com.example.sanayirehberim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp-AxgvREKYOjC_sMH93H4aWMLh4sJ35g',
    appId: '1:1013497024846:web:e9ebf4bdb1e80e0638ce1f',
    messagingSenderId: '1013497024846',
    projectId: 'sanayirehberim-1e438',
    authDomain: 'sanayirehberim-1e438.firebaseapp.com',
    storageBucket: 'sanayirehberim-1e438.firebasestorage.app',
    measurementId: 'G-C3L8FPP5ZP',
  );
}
